version: '3.8'

services:
  frontend:
    build: ./iara-ui
    image: iara-ui:latest
    ports:
      - "9090:80"
    environment:
      - VITE_API_URL=http://backend:8080/
    depends_on:
      - backend

  backend:
    build: ./iara-server
    image: iara-server:latest
    ports:
      - "8080:8080"