version: '3.8'

services:
  frontend:
    build: ./iara-ui
    image: iara-ui:latest
    ports:
      - "9090:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./iara-server
    image: iara-server:latest
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=cXS8WsBnuGGPGiuYJpNDaBhhrwCOwyk1iv7XeRW52tStOlt1kq
      - CLIENT_URL=http://localhost:9090