name: Build IARA

on: [workflow_dispatch]

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: joyned

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iara-server
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
    
    - name: Build Backend
      run: |
        ls -la
        cd iara-server/
        chmod +x ./gradlew
        ./gradlew build -x test
    
    - name: Build Docker image for server
      run: |
        cd iara-server/
        docker build -t $REGISTRY/$IMAGE_PREFIX/iara-server:latest -t $REGISTRY/$IMAGE_PREFIX/iara-server:${{ github.sha }} .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push Docker image for server
      run: |
        docker push $REGISTRY/$IMAGE_PREFIX/iara-server:latest
        docker push $REGISTRY/$IMAGE_PREFIX/iara-server:${{ github.sha }}

    