name: Test Server

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 21
        architecture: x64
    - uses: cicirello/jacoco-badge-generator@v2.3.0
      with:
        jacoco-csv-file: iara-server/build/reports/jacoco/jacocoTestReport.csv
    - name: Clean, Build & Test
      run: cd iara-server/ && ./gradlew clean build test
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.outputs.coverage }}"